version: '3.4'

services:
  nginx:
    image: nginx:1.13
    container_name: bot.nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    depends_on:
      - python

  db:
    image: mysql:5.7
    container_name: bot.db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - bot-db:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

  python:
    build: ./docker/python
    container_name: bot.python
    command: >
      sh -c 'python run.py &
      uwsgi --socket :8001 --module bot.wsgi'
    volumes:
      - ./src:/code
      - ./src/static:/static
    expose:
      - "8001"
    depends_on:
      - db

  # vuejs:
  #   build: ./docker/vuejs
  #   container_name: bot.vuejs
  #   command: >
  #     sh -c 'cd /app/bot/vuejs &&
  #     npm install &&
  #     npm run build-watch'
  #   volumes:
  #     - ./src:/app
  #     #- ./src/bot/static/assets:/app/bot/vuejs/dist
  #     # - node-modules:/app/bot/vuejs/node_modules

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bot.phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 8080:80

volumes:
  bot-db:
    driver: local
  # node-modules:
  #   driver: local
