# Generated by Django 2.2.1 on 2019-06-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.PositiveIntegerField()),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_tel', models.CharField(max_length=10)),
                ('employee_tel_mobile', models.CharField(max_length=11)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('employee_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Division')),
            ],
        ),
    ]
